### ISSUE TITLE
build.py error

### ISSUE THREAD

**Issue by primej8** [mkwcat/gecko-codes#4]
when build.py is run i get "Traceback (most recent call last):
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 195, in <module>
    run_build("nsmbw", "Lift-Anything")
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 127, in run_build
    result = subprocess.run([path_cc, "-S", path_src, "-Isource", "-o-", "-D__POWERPC__"] + ccflags.split(" ") + warning_flags.split(" "), stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\user\Downloads\gecko-codes-master\gecko-codes-master> & C:/Python312/python.exe c:/Users/user/Downloads/gecko-codes-master/gecko-codes-master/build.py
Traceback (most recent call last):
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 195, in <module>
    run_build("nsmbw", "Lift-Anything")
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 127, in run_build
    result = subprocess.run([path_cc, "-S", path_src, "-Isource", "-o-", "-D__POWERPC__"] + ccflags.split(" ") + warning_flags.split(" "), stdout=subprocess.PIPE)
PS C:\Users\user\Downloads\gecko-codes-master\gecko-codes-master> & C:/Python312/python.exe c:/Users/user/Downloads/gecko-codes-master/gecko-codes-master/build.py
Traceback (most recent call last):
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 195, in <module>
    run_build("nsmbw", "Lift-Anything")
  File "c:\Users\user\Downloads\gecko-codes-master\gecko-codes-master\build.py", line 127, in run_build
    result = subprocess.run([path_cc, "-S", path_src, "-Isource", "-o-", "-D__POWERPC__"] + ccflags.split(" ") + warning_flags.split(" "), stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified"

**Comment by mkwcat** [comment]
did you set the `DEVKITPPC` environment variable to a valid path?
